name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
jobs:
  date_job:
    runs-on: ubuntu-18.04
    steps:
      - name: It is
        run: |
          echo date
jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Directory
        run: |
          ls -l
          
          
